#!/usr/bin/env sh
#
# Rofi powered menu to change awesome tiling

floating=''
lefttile=''
bottomtile=''
fairtile=''
fairh=''
mag=''

chosen=$(printf '%s;%s;%s;%s;%s;%s\n' "$floating" "$lefttile" "$bottomtile" "$fairtile" "$fairh" "$mag" \
	| rofi -theme 'menus/awesome-tiling.rasi' \
           -dmenu \
	   -sep ';' \
           -selected-row 1)

case "$chosen" in
    "$mag")		action="awful.layout.set(awful.layout.suit.magnifier)" ;;
    "$fairh")		action="awful.layout.set(awful.layout.suit.fair.horizontal)" ;;
    "$fairtile")	action="awful.layout.set(awful.layout.suit.fair)" ;;
    "$bottomtile")   	action="awful.layout.set(awful.layout.suit.tile.bottom)" ;;
    "$lefttile")  	action="awful.layout.set(awful.layout.suit.tile)" ;;
    "$floating") 	action="awful.layout.set(awful.layout.suit.floating)" ;;
    *)          exit 1 ;;
esac

# The variable can be used as a command's options, so it shouldn't be quoted.
# shellcheck disable=2086
awesome-client $action
