#!/usr/bin/env sh
#
# Rofi powered menu to change awesome tiling

shutdown=''
reboot=''
hibernate=''
sus=''
lock=''
logoff=''

chosen=$(printf '%s;%s;%s;%s;%s;%s\n' "$shutdown" "$reboot" "$hibernate" "$sus" "$lock" "$logoff" \
	| rofi -theme 'menus/shutdown.rasi' \
           -dmenu \
	   -sep ';' \
           -selected-row 1)

case "$chosen" in
    "$shutdown")	systemctl poweroff ;;
    "$reboot")		systemctl reboot ;;
    "$hibernate")	$HOME/.config/awesome/scripts/lock_screen.sh && systemctl hibernate ;;
    "$sus")   		$HOME/.config/awesome/scripts/lock_screen.sh && systemctl suspend ;;
    "$lock")  		$HOME/.config/awesome/scripts/lock_screen.sh ;;
    "$logoff")	 	awesome-client "awesome.quit()" ;;
    *)     :      ;;
esac

# The variable can be used as a command's options, so it shouldn't be quoted.
# shellcheck disable=2086
